name: Build and push to replicate

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main

    - name: Setup Cog
      uses: replicate/setup-cog@v1
      with:
        token: ${{ secrets.REPLICATE_API_TOKEN }}

    - name: Download Model
      run: |
        mkdir model
        python -c "import torch;from diffusers import AutoPipelineForText2Image;AutoPipelineForText2Image.from_pretrained('stabilityai/sdxl-turbo', torch_dtype=torch.float16, variant='fp16', cache_dir='model')"


    - name: Push to Replicate
      run: cog push r8.im/jonasloos/sdxl-turbo-h-space-modification-model
