name: Build and push to replicate

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Free up space
      run: |
        df -h
        sudo apt-get remove -y '^ghc-8.*' || true
        sudo apt-get remove -y '^dotnet-.*' || true
        sudo apt-get remove -y '^llvm-.*' || true
        sudo apt-get remove -y 'php.*' || true
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel || true
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
        echo "Removing large directories"
        rm -rf /usr/share/dotnet/ || true
        df -h

    - name: Setup Cog
      uses: replicate/setup-cog@v1
      with:
        token: ${{ secrets.REPLICATE_API_TOKEN }}

    - name: Push to Replicate
      run: cog push r8.im/jonasloos/sdxl-turbo-h-space-modification-model
